### ISSUE TITLE
`yq` is a hard requirement for `make`

### ISSUE THREAD

**Issue by hackeryarn** [getoutreach/devbase#457]
Running `make` on a fresh build requires `yq` to even pull down `devbase`. There is an `asdf` plugin for `yq`, but it installs the Go `yq` and not the Python `yq` (and I believe that the Python `yq` is expected). 

In the short term, this hard dependency should be documented. For the long term, should this be an be an `asdf` plugin of its own, or should the project move to the Go `yq` which is much more portable and doesn't require Python.

**Comment by tomassusovsky-outreach** [comment]
@jaredallard note: 
I encountered this weird issue with job running in shared/testbed-docker executor, where it skips installing `yq`, because Python yq is detected, but in the next sept (shared/setup_environment), job failed, because `yq` command was not available:
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/89918613/236240058-ee4e4307-f529-47dd-8fd3-e33f30c67b73.png">

in shared/testbed-machine executor yq was installed correctly. I needed to use  shared/testbed-machine executor for my task due to other factors, so it's not a blocking issue (but someone else could run into this curious issue).

**Comment by jaredallard** [comment]
That's... odd. It's probably not available in path for the next step somehow, but would need to see the config definition.

**Comment by malept** [comment]
It appears [`gojq` supports YAML](https://github.com/itchyny/gojq?tab=readme-ov-file#difference-to-jq):
![gojq supports reading from YAML input (`--yaml-input`) while jq does not. gojq also supports YAML output (`--yaml-output`).](https://github.com/getoutreach/devbase/assets/11417/cd034105-35ca-4293-8f04-9c8e61d0528f)
